FROM ros:galactic

RUN sudo apt update && sudo apt install -y software-properties-common wget curl
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - 
RUN sudo add-apt-repository -y 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'
RUN sudo apt update && sudo apt install -y clang-format-16 clangd-16 clang-16 clang-tools-16 clang-tidy-16
RUN sudo apt update && sudo apt install -y ros-galactic-ros2-control ros-galactic-control-msgs ros-galactic-control-toolbox ros-galactic-ros2controlcli ros-galactic-rclcpp-action 
RUN sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-16 100
RUN sudo update-alternatives --install /usr/bin/clangd clangd /usr/bin/clangd-16 100
RUN sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-16 100
RUN sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-16 100
RUN sudo apt update && sudo apt install -y gdb

ENTRYPOINT ["/ros_entrypoint.sh"]
